/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cescoandtomas.managemore;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class AnalyticsPanel extends javax.swing.JPanel{
       HashMap<String, String> facilities = new HashMap<>();
        public JDialog jd;
        public TableInfo info;
        
    /*
     * Creates new form InsertPanel
     */
        
    public AnalyticsPanel(JDialog jd, TableInfo info) {
        // we store the dialog box that created this panel
        //so we can close it when we are done
        this.jd = jd;
        this.info = info;
        initComponents();
        setupComboBox();
        analyzeData();
       
        
       
    }
    
    
    
    private void setupComboBox(){
        
       
        //initializes the values of the combo boxes to hold the attributes of the table.
        //first remove the sample entries from all
        jComboBox1.removeAllItems(); //facility 
        
        
        
        //this function takes the name and ID of each object and stores them as a map.
        //the product and facility ID map to its name.
        //so after the user enters all input, a query can be made to perform the result.
        
        try{
        Connection con = Frame.getCon(); // get the connection for the queries we are about to do
       
        //get all facilities
        String stmt = "SELECT DISTINCT * FROM facility";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(stmt);
        
       
        while(rs.next()){
            
        String facilityID = rs.getString("facilityID");
        String facilityName = rs.getString("name");
        
        facilities.put(facilityName, facilityID);
          
        
        
        jComboBox1.addItem(facilityName);
        
        
        }
        
        
        
    }catch(Exception e){
                e.printStackTrace();
                }
        
        
    }
        
    
   
    
    private void analyzeData(){
        try{
        Connection con = Frame.getCon();
        Statement st = con.createStatement();
        //this panel calculates the following analytics:
        //the Vendor who has the most products sold to a facility
        //Item most in stock
        //amount of employees
        String favVendor = "SELECT * FROM vendor join sells join product join purchases join stock join facility WHERE"
                + " vendor.vendorID = sells.vendorID AND sells.productID = product.productID AND product.productID = purchases.productID AND purchases.facilityID = stock.facilityID "
                + "AND stock.facilityID = " + facilities.get(jComboBox1.getSelectedItem())
                + " ORDER BY stock.amount DESC";
        //we need to get the vendor name from this query
        System.out.println(favVendor);
        ResultSet rs = st.executeQuery(favVendor);
        
        rs.next();//gives us the first elemenet, which is the vendor with the most stock.
        String vendorName = rs.getString("vendor.name");
        String productName = rs.getString("product.name");
        String amount = rs.getString("stock.amount");
         
          //update the jLabels on the panel
          
          jLabel4.setText(productName);
          jLabel6.setText(vendorName);
          jLabel5.setText(amount);
        
       

        //number of employees
        String empCount = "SELECT DISTINCT count(*)FROM facilityEmployee WHERE facilityID = " + facilities.get(jComboBox1.getSelectedItem());
        rs = st.executeQuery(empCount);
        rs.next();
        String count = rs.getString("count(*)");
        
        //set jlabel
        jLabel12.setText(count);
        
       
        }catch(Exception e){
            e.printStackTrace();
            
            
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Facility: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("product");

        jLabel5.setText("amount");

        jLabel6.setText("vendor");

        jLabel2.setText("Most Stocked Product: ");

        jLabel3.setText("Amount: ");

        jLabel10.setText("Vendor: ");

        jLabel7.setText("Stock Information");

        jLabel8.setText("General Information");

        jLabel9.setText("Total Amount of Employees: ");

        jLabel12.setText("employeeCount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //this is the cancel button
        //closes the dialog box
        jd.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //this fires when the selection of facility changes
        //must do new analytics
        
        analyzeData();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
